In [2]:
import numpy as np
import cv2

In [5]:
resim1=cv2.imread("s_ev1.jpg")
resim2=cv2.imread("s_futbol1.jpg")

resim1=resim1[0:200,0:200]
resim2=resim2[0:200,0:200]


print(resim1[100,190])
print(resim2[150,190])

cv2.imshow("ev",resim1)
cv2.imshow("saha",resim2)

toplam=cv2.add(resim1,resim2)
agirlikliToplam=cv2.addWeighted(resim1,0.3,resim2,0.7,0)
cv2.imshow("toplanmış",toplam)
cv2.imshow("toplanmış2",agirlikliToplam)


print(resim1[100,190]+resim2[150,190])

cv2.waitKey(0)
cv2.destroyAllWindows()

[49 48 56]
[ 56 134  97]
[105 182 153]
