In [1]:
import numpy as np
import cv2

In [19]:
resim=cv2.imread("s_ev1.jpg")
ikiKatBuyuk=cv2.pyrUp(resim)
ikikatKucuk=cv2.pyrDown(resim)

print(ikikatKucuk.shape)
print(resim.shape)
print(ikiKatBuyuk.shape)

cv2.imshow("orjinal",resim)
cv2.imshow("İki kat büyük",ikiKatBuyuk)
cv2.imshow("İki kat küçük",ikikatKucuk)

cv2.waitKey(0)
cv2.destroyAllWindows()

(123, 200, 3)
(245, 400, 3)
(490, 800, 3)


In [21]:
import numpy as np
import cv2

In [31]:
resim=np.zeros((300,300,3),dtype="uint8")
print(resim)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
